name: opengwmail
version: 1.1.1
summary: openGWMail
description: openGWMail
confinement: strict
grade: stable
icon: snap/gui/app.png
apps:
  opengwmail:
    command: env TMPDIR=$XDG_RUNTIME_DIR desktop-launch $SNAP/openGWMail
    plugs:
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
parts:
  app:
    plugin: dump
    stage-packages:
      - libnotify4
      - libappindicator1
      - libxtst6
      - libnss3
      - libxss1
      - fontconfig-config
      - gconf2
      - libasound2
      - pulseaudio
    source: openGWMail-linux-x64
    after:
      - desktop-glib-only
